django_source/Tally/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url('', include('testtool.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

django_source/testtool/main/urls.py
from django.conf.urls import *


urlpatterns = patterns('testtool.main.views',
    # Subject URLs
    url(r'^$',                                  'index',  name='home'),
    url(r'^(?P<test_instance_id>\d+)/tally/$',  'tally',  name='tally'),
    url(r'^(?P<test_instance_id>\d+)/status/$', 'status', name='status'),
    
    # Desktop App URLs
    url(r'^(?P<test_instance_id>\d+)/init/$',      'init_test_instance', name='init_test_instance'),
    url(r'^(?P<test_instance_id>\d+)/get_media/$', 'get_media',          name='get_media'),
)

django_source/testtool/manager/urls.py
from django.conf.urls import *
from testtool.manager.views import CreateTest, DisplayTest, EditTest, CreateTestInstance, DisplayTestInstance, EditTestInstance

urlpatterns = patterns('testtool.manager.views',

    ### Tests
    url(r'^tests/$',                                'list_tests',          name='list_tests'),
    url(r'^tests/(?P<test_id>\d+)/share$',          'share_export_obj',    {'action':'share'},   name='share_test'),
    url(r'^tests/(?P<test_id>\d+)/export$',         'share_export_obj',    {'action':'export'},  name='export_test'),
    url(r'^tests/(?P<test_id>\d+)/unshare$',        'unshare_delete_test', {'action':'unshare'}, name='unshare_test'),
    url(r'^tests/(?P<test_id>\d+)/delete$',         'unshare_delete_test', {'action':'delete'},  name='delete_test'),
    url(r'^tests/(?P<test_id>\d+)/addvideo/$',      'add_video',           name='add_video'),
    url(r'^deletevideo/(?P<video_id>\d+)/$',        'delete_video',        name='delete_video'),
    url(r'^tests/(?P<test_id>\d+)/addtestcase/$',   'add_test_case',       name='add_test_case'),
    url(r'^deletetestcase/(?P<test_case_id>\d+)/$', 'delete_test_case',    name='delete_test_case'),
    
    ### Test Instances
    url(r'^tests/(?P<test_id>\d+)/instances/$',                                  'list_test_instances',   name='list_test_instances'),
    url(r'^tests/(?P<test_id>\d+)/instances/(?P<test_instance_id>\d+)/run/$',    'run_test_instance',     name='run_test_instance'),
    url(r'^tests/(?P<test_id>\d+)/instances/(?P<test_instance_id>\d+)/share$',   'share_export_obj',      {'action':'share'},  name='share_test_instance'),
    url(r'^tests/(?P<test_id>\d+)/instances/(?P<test_instance_id>\d+)/export$',  'share_export_obj',      {'action':'export'}, name='export_test_instance'),
    url(r'^tests/(?P<test_id>\d+)/instances/(?P<test_instance_id>\d+)/unshare$', 'unshare_delete_test_instance',  {'action':'unshare'}, name='unshare_test_instance'),
    url(r'^tests/(?P<test_id>\d+)/instances/(?P<test_instance_id>\d+)/delete$',  'unshare_delete_test_instance',  {'action':'delete'}, name='delete_test_instance'),
    
    ### Misc
    url(r'^logbook/$',                          'log_book',       name='log_book'),
    url(r'^(?P<test_instance_id>\d+)/mirror/$', 'mirror_score',   name='mirror_score'),
    url(r'^testerprofile/$',                    'render_profile', name='tester_profile'),
    url(r'^help/$',                             'help',           name='help'),
)

# Class-based views
urlpatterns += patterns('',
    url(r'^tests/create/$',                                                   CreateTest.as_view(),          name='create_test'),
    url(r'^tests/(?P<test_id>\d+)/$',                                         DisplayTest.as_view(),         name='display_test'),
    url(r'^tests/(?P<test_id>\d+)/edit/$',                                    EditTest.as_view(),            name='edit_test'),
    url(r'^tests/(?P<test_id>\d+)/instances/create$',                         CreateTestInstance.as_view(),  name='create_test_instance'),
    url(r'^tests/(?P<test_id>\d+)/instances/(?P<test_instance_id>\d+)/$',     DisplayTestInstance.as_view(), name='display_test_instance'),
    url(r'^tests/(?P<test_id>\d+)/instances/(?P<test_instance_id>\d+)/edit$', EditTestInstance.as_view(),    name='edit_test_instance'),
)

django_source/testtool/urls.py
from django.conf.urls import *


# URLS from all sub-apps
urlpatterns = patterns('',
    url(r'^', include('testtool.main.urls')),
    url(r'^', include('testtool.manager.urls')),
    url(r'^', include('testtool.registration.urls')),
)

django_source/testtool/models/registration.py
from django.db import models
from django.contrib.auth.models import User

GENDER_CHOICES = (
    ('M', 'Male'),
    ('F', 'Female'),
)

class UserProfile(models.Model):
    birth_date = models.DateField()
    sex        = models.CharField(max_length=1, choices = GENDER_CHOICES)
    user       = models.OneToOneField(User)
        
    class Meta:
        app_label = 'testtool'
    def __unicode__(self):
        return self.user.username

django_source/testtool/models/test_modes.py
from django.db import models
from testtool.models.main import TestCaseInstance
from testtool.models.registration import UserProfile


class Score(models.Model):
    test_case_instance = models.ForeignKey(TestCaseInstance)
    subject            = models.ForeignKey(UserProfile)
    
    class Meta:
        app_label = 'testtool'
        abstract = True
        
        
class ScoreSSCQE(Score):
    value     = models.DecimalField(max_digits=5, decimal_places=2)
    timestamp = models.DateTimeField(auto_now_add=True)
    
    def __unicode__(self):
        return '%s : %s : %5.2f' % (str(self.test_case_instance), str(self.subject), self.value)
        
        
class ScoreDSIS(Score):
    value = models.IntegerField()
    
    def __unicode__(self):
        return '%s : %s : %d' % (str(self.test_case_instance), str(self.subject), self.value)
        
        
class ScoreDSCQS(Score):
    value1 = models.DecimalField(max_digits=3, decimal_places=2)
    value2 = models.DecimalField(max_digits=3, decimal_places=2)
    
    def __unicode__(self):
        return '%s : %s : %4.2f %4.2f' % (str(self.test_case_instance), str(self.subject), self.value1, self.value2)

django_source/UCSDSubjectiveTestingTool/manager/forms.py
from django import forms
from django.forms import ModelForm, ModelMultipleChoiceField
from GenericTest.models import *

class CreateTestForm(ModelForm):
    collaborator = ModelMultipleChoiceField(queryset = UserProfile.objects.filter(user__groups__name__iexact='Testers'), required=False)
    
    class Meta:
        model = Test
        exclude = ('owner','create_time')
        
class DisplayTestForm(ModelForm):
    class Meta:
        model = Test
        exclude = ('title',)
            
class CreateTestInstanceForm(ModelForm):
    class Meta:
        model = TestInstance
        exclude = ('test', 'owner', 'run_time', 'counter')
        
        
class DisplayTestInstanceForm(ModelForm):
    class Meta:
        model = TestInstance
        exclude = ('counter')

django_source/testtool/manager/forms.py
from django import forms
from testtool.models import *
    
class CreateTestForm(forms.ModelForm):
    class Meta:
        model = Test
        exclude = ('owner','collaborators')

        
class EditTestForm(forms.ModelForm):
    method = forms.CharField(widget=forms.TextInput(attrs={'readonly':True})) # make the field readonly
    class Meta:
        model = Test
        exclude = ('owner','collaborators')

    # to ensure that the readonly value won't be overridden by a POST
    def clean_method(self):
        return self.instance.method
    

class DisplayTestForm(forms.ModelForm):
    create_time = forms.DateTimeField()
    class Meta:
        model = Test
        widgets = {'owner': forms.TextInput(), 'method': forms.TextInput()}
        
    def __init__(self, *args, **kwargs):
        super(DisplayTestForm, self).__init__(*args, **kwargs)
        # set fields to read-only
        for key in ['owner', 'create_time', 'method', 'collaborators', 'title', 'description']:
            self.fields[key].widget.attrs['readonly'] = True
        # override initial values
        self.initial['owner'] = self.instance.owner.user.username
        # define querysets
        self.fields['collaborators'].queryset = self.instance.collaborators.all()
        # define extra fields
        self.fields['create_time'].label = self.instance._meta.get_field('create_time').verbose_name
        self.fields['create_time'].initial = self.instance.create_time

    # to ensure that the readonly value won't be overridden by a POST
    def clean_collaborators(self):
        return self.instance.collaborators.all()
    def clean_title(self):
        return self.instance.title
    def clean_description(self):
        return self.instance.description
    def clean_method(self):
        return self.instance.method


class CreateTestCaseFormDiscrete(forms.Form):
    filename1 = forms.ModelChoiceField(label = 'Reference video', queryset = Video.objects.all(), required = True)
    filename2 = forms.ModelChoiceField(label = 'Test video', queryset = Video.objects.all(), required = True)
    repeat    = forms.IntegerField(min_value=1,max_value=10,required=True,initial=1)
    
    
class CreateTestCaseFormSSCQE(forms.Form):
    filename = forms.ModelChoiceField(label = 'Video', queryset = Video.objects.all(), required = True)
    repeat   = forms.IntegerField(min_value=1,max_value=10,required=True,initial=1)

        
class CreateEditTestInstanceForm(forms.ModelForm):
    available = forms.ModelMultipleChoiceField(label='Available subjects', queryset=UserProfile.objects.filter(user__groups__name__iexact='Subjects'), required=False)
    subjects = forms.ModelMultipleChoiceField(label='Enrolled subjects', queryset=UserProfile.objects.filter(user__groups__name__iexact='Subjects'), required=False)
    
    class Meta:
        model = TestInstance
        fields = ('path', 'location', 'description', 'schedule_time', 'available', 'subjects')
        
    def __init__(self, *args, **kwargs):
        super(CreateEditTestInstanceForm, self).__init__(*args, **kwargs)
        status = ''
        if self.instance.pk:
            status = self.instance.get_status()
            if status=='Complete':
                self.fields['path'].widget.attrs['readonly'] = True
                self.fields['schedule_time'].widget.attrs['readonly'] = True
                self.fields['subjects'].widget.attrs['readonly'] = True
                self.fields['available'].widget.attrs['readonly'] = True
            elif status=='Incomplete':
                self.fields['schedule_time'].widget.attrs['readonly'] = True
            self.fields['available'].queryset = UserProfile.objects.filter(user__groups__name__iexact='Subjects').exclude(pk__in=self.instance.subjects.all().values_list('pk', flat=True))
        self.status = status
        
    def clean_path(self):
        if self.instance.pk and self.status=='Complete':
            return self.instance.path
        return self.cleaned_data['path']
    def clean_schedule_time(self):
        if self.instance.pk and self.status in ['Complete', 'Incomplete']:
            return self.instance.schedule_time
        return self.cleaned_data['schedule_time']
    # def clean_subjects(self):                                 # this code seems correct, but is causing a bug.  When a test instance is 'Complete',
        # if self.instance.pk and self.status=='Complete':      # and the user clicks 'edit' and then 'save', all of the subjects are removed from
            # return self.instance.subjects.all()               # the test instance.  Commenting out this function removes this problem, but makes
        # return self.cleaned_data['subjects']                  # the edit form susceptible to POST attacks.  However, this is a very small risk.
        
        
class DisplayTestInstanceForm(forms.ModelForm):
    create_time = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'readonly':True}))
    status = forms.CharField(widget=forms.TextInput(attrs={'readonly':True}))
    class Meta:
        model = TestInstance
        fields = ('status', 'create_time', 'test', 'owner', 'path', 'location', 'description', 'schedule_time', 'run_time', 'collaborators', 'subjects')
        widgets = {'test': forms.TextInput(), 'owner': forms.TextInput()}   # do not use default dropdown menu
        
    def __init__(self, *args, **kwargs):
        super(DisplayTestInstanceForm, self).__init__(*args, **kwargs)
        # set fields to read-only
        for key in ['test', 'owner', 'collaborators', 'subjects', 'schedule_time', 'run_time', 'path', 'description', 'location']:
            self.fields[key].widget.attrs['readonly'] = True
        # override initial values
        self.initial['test'] = self.instance.test.__unicode__()
        self.initial['owner'] = self.instance.owner.user.username
        # define querysets
        self.fields['collaborators'].queryset = self.instance.collaborators.all()
        self.fields['subjects'].queryset = self.instance.subjects.all()
        # define extra fields
        self.fields['create_time'].label = self.instance._meta.get_field('create_time').verbose_name
        self.fields['create_time'].initial = self.instance.create_time
        self.fields['status'].label = 'Status'
        self.fields['status'].initial = self.instance.get_status()
        
    # to ensure that the readonly value won't be overridden by a POST
    def clean_test(self):
        return self.instance.test
    def clean_owner(self):
        return self.instance.owner
    def clean_collaborators(self):
        return self.instance.collaborators.all()
    def clean_subjects(self):
        return self.instance.subjects.all()
    def clean_schedule_time(self):
        return self.instance.schedule_time
    def clean_run_time(self):
        return self.instance.run_time
    def clean_path(self):
        return self.instance.path
    def clean_description(self):
        return self.instance.description
    def clean_location(self):
        return self.instance.location
    
    
class ExportDataForm(forms.Form):
    format = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple, choices = (#('report', 'Report (.pdf)'),
                                                                                       ('spreadsheet', 'Spreadsheet (.csv)'),
                                                                                       ('matlab','MATLAB (.mat)'),
                                                                                       ('python','Python (.py)')))

                                                                                       
class ShareObjectForm(forms.Form):
    available = forms.ModelMultipleChoiceField(label='Available collaborators', queryset=UserProfile.objects.filter(user__groups__name__iexact='Testers'), required=False)
    share_with = forms.ModelMultipleChoiceField(queryset=UserProfile.objects.filter(user__groups__name__iexact='Testers'))

        
class DisplayUserForm(forms.ModelForm):
    class Meta:
        model = User
        exclude = ('password','is_active','is_staff','is_superuser','groups','user_permissions','last_login')
    
    def __init__(self, *args, **kwargs):
        super(DisplayUserForm, self).__init__(*args, **kwargs)
        # set fields to read-only
        for key in ['username', 'first_name', 'last_name', 'email', 'date_joined']:
            self.fields[key].widget.attrs['readonly'] = True
    
    def clean_username(self):
        return self.instance.username
    def clean_first_name(self):
        return self.instance.first_name
    def clean_last_name(self):
        return self.instance.last_name
    def clean_email(self):
        return self.instance.email
    def clean_date_joined(self):
        return self.instance.date_joined
    
    
class DisplayUserProfileForm(forms.ModelForm):
    sex = forms.CharField(widget=forms.TextInput(attrs={'readonly':True}))
    class Meta:
        model = UserProfile
        exclude = ('user')
        
    def __init__(self, *args, **kwargs):
        super(DisplayUserProfileForm, self).__init__(*args, **kwargs)
        self.fields['birth_date'].widget.attrs['readonly'] = True
        
    def clean_sex(self):
        return self.instance.sex
    def clean_birth_date(self):
        return self.instance.birth_date

django_source/templates/testtool/manager/base_manager.html
{% extends "testtool/registration/base_manager_login.html" %}

{% load staticfiles %}
{% load manager_tags %}

{% block head_1 %}
    <style type="text/css">
        .profile-hover:hover .dropdown-menu{
            display: block;    
        }
        .info {
            padding: 3px 15px;
            margin: 0px;
        }
    </style>
    <link type="text/css" href="{% static 'css/tally.css' %}" rel="stylesheet" >
    <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bootstrap/js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/json2.js' %}"></script>
    {% block head %}
    {% endblock head %}
{% endblock head_1 %}

{% block navbar %}
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container-fluid">
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <a class="brand" href="{% url 'home' %}">Tally</a>
                <div class="btn-group pull-right profile-hover">
                    <button class="btn dropdown-toggle">
                        <i class="icon-user"></i> {{ request.user.username }}
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu">
                        <li class="info">{{ request.user.first_name }} {{ request.user.last_name }}</li>
                        <li class="info">{{ request.user.email }}</li>
                        <li class="divider"></li>
                        <li><a href="{% url 'profile' %}"><i class="icon-th-list"></i> Profile</a></li>
                        <li><a href="{% url 'logout' %}"><i class="icon-off"></i> Sign Out</a></li>
                    </ul>
                </div>
                <div class="nav-collapse">
                    <ul class="nav pull-right">
                        <li class="{% active request 'home' %}"><a href="{% url 'home' %}">Home</a></li>
                        <li><a href="http://canbal.github.com/Tally" target="_blank">Tally on Git</a></li>
                        <li class="{% active request 'help' %}"><a href="{% url 'help' %}">Help</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock navbar %}

{% block row %}
    <div class="span3">
            <ul class="well nav nav-list tally-sidenav">
                <li class="nav-header">Tests</li>
                <li class="{% active request 'list_tests' %}"><a href="{% url 'list_tests' %}"><i class="icon-list"></i> My Tests</a></li>
                <li class="{% active request 'create_test' %}"><a href="{% url 'create_test' %}"><i class="icon-file"></i> Create New Test</a></li>
                <li class="nav-header">Tools</li>
                <li class="{% active request 'log_book' %}"><a href="{% url 'log_book' %}"><i class="icon-book"></i> Log Book</a></li>
            </ul>
    </div>
    <div class="span9">
        <h1>{% block header %}Default header{% endblock header %}</h1>
        <br/><br/>
        {% if alert %}
        <div class="alert alert-{{ alert_class }} alert-block">
            <a class="close" data-dismiss="alert" href="#">&times</a>
            <b>{{ alert }}</b>
            </div>
        {% endif %}
        {% if error %}
        <div class="alert alert-error alert-block">
            <a class="close" data-dismiss="alert" href="#">&times</a>
            <b>{{ error }}</b>
        </div>
        {% else %}
            {% block content %}
                <p>Default content</p>
            {% endblock content %}
        {% endif %}
        {% block buttons %}
        {% endblock buttons %}
    </div>
{% endblock row %}

{% block end_scripts %}
    <script src="{% static 'bootstrap/js/bootstrap-transition.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap-alert.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap-modal.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap-dropdown.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap-scrollspy.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap-tab.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap-tooltip.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap-popover.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap-button.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap-collapse.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap-carousel.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap-typeahead.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap-affix.js' %}"></script>
    <script src="{% static 'js/tally.js' %}"></script>
{% endblock end_scripts %}

django_source/templates/testtool/manager/create_edit_test_instance_share.html
{% extends "testtool/manager/base_manager.html" %}

{% block head %}
<style>
    ul {
        list-style: none;
    }
</style>
<script type="text/javascript">
    $().ready(function() {
        $('#add_btn').click(function() {
            return !$('#id_available option:selected').remove().appendTo('#id_to_enroll').removeAttr("selected");
        });
        $('#remove_btn').click(function() {
            return !$('#id_to_enroll option:selected').remove().appendTo('#id_available').removeAttr("selected");
        });
        $('form').submit(function() {
            $('#id_to_enroll option').each(function(i) {
                $(this).attr("selected", "selected");
            });
        });
    });
</script>
{% endblock head %}

{% block header %}
    {{ header }}
{% endblock header %}

{% block content %}
<form class="form-horizontal" action="" method="post">
    {% csrf_token %}
    <span style="color:red;font-weight:bold;font-size:1.1em">
    {{ form.non_field_errors }}
    </span>
    {% for field in form %}
        <div class="control-group{% if field.errors %} error{% endif %}">
            <label class="control-label" for="id_{{ field.html_name }}">{{ field.label }}</label>
            <div class="controls">
                {% if field.html_name == to_enroll %}
                <select {% if field.field.widget.attrs.readonly %}readonly="True"{% endif %} multiple="multiple" name="{{ field.html_name }}" id="id_to_enroll">
                    {% for e in enrolled %}
                    <option value="{{ e.pk }}">{{ e.user.username }}</option>
                    {% endfor %}
                </select>
                <button {% if field.field.widget.attrs.readonly %}disabled{% endif %} class="btn btn-small btn-danger" type="button" id="remove_btn">Remove</button>
                {% else %} 
                    {{ field }}
                    {% if field.html_name == "available" %}
                        <button {% if field.field.widget.attrs.readonly %}disabled{% endif %} class="btn btn-small btn-success" type="button" id="add_btn">Add</button>
                    {% endif %}
                {% endif %}
                {% if field.errors %}
                <ul class="help-inline">
                    {% for error in field.errors %}
                    <li>{{ error }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
            </div>
        </div>
    {% endfor %}
    <div class="form-actions">
        <a class="btn" href="{{ cancel_url }}">Cancel</a>
        <input type="submit" class="btn btn-primary" value="{{ submit_value }}"/>
    </div>
</form>
{% endblock content %}

django_source/templates/testtool/manager/create_test.html
{% extends "testtool/manager/base_manager.html" %}

{% block head %}
<style>
    ul {
        list-style: none;
    }
</style>
{% endblock head %}

{% block header %}
    Create a new test
{% endblock header %}

{% block content %}
<form class="form-horizontal" id="test_create_form" action="" method="post" enctype="multipart/form-data">
	{% csrf_token %}
	<span style="color:red;font-weight:bold;font-size:1.1em">
	{{ form.non_field_errors }}
	</span>
    {% for field in form %}
    	<div class="control-group{% if field.errors %} error{% endif %}">
	    	<label class="control-label" for="id_{{ field.html_name }}">{{ field.label }}</label>
	    	<div class="controls">
	    		{{ field }}
                {% if field.errors %}
                	<ul class="help-inline">
                        {% for error in field.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>
		</div>
	{% endfor %}
	<div class="form-actions">
	    <a class="btn" href="{% url 'home' %}">Cancel</a>
        <input type="submit" class="btn btn-primary" id="create_button" value="Create" />
    </div>
</form>
{% endblock content %}


django_source/templates/testtool/manager/create_test_case.html
{% extends "testtool/manager/base_manager.html" %}

{% block head %}
<style>
    ul {
        list-style: none;
    }
</style>
{% endblock head %}

{% block header %}
    {{ header }}
{% endblock header %}

{% block content %}
<form class="form-horizontal" id="test_case_create_form" action="" method="post" enctype="multipart/form-data">
	{% csrf_token %}
	<span style="color:red;font-weight:bold;font-size:1.1em">
	{{ form.non_field_errors }}
	</span>
    {% for field in form %}
    	<div class="control-group{% if field.errors %} error{% endif %}">
	    	<label class="control-label" for="id_{{ field.html_name }}">{{ field.label }}</label>
	    	<div class="controls">
	    		{{ field }}
                {% if field.errors %}
                	<ul class="help-inline">
                        {% for error in field.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>
		</div>
	{% endfor %}
	<div class="form-actions">
        <a class="btn" href="{% url 'edit_test' test_id=test_id %}">Cancel</a>
        <input type="submit" class="btn btn-primary" id="add_button" value="Add" />
    </div>
</form>
{% endblock %}

django_source/templates/testtool/manager/display_test_instance.html
{% extends "testtool/manager/base_manager.html" %}

{% block head %}
<style>
    .form-container form {
        display: inline;
    }
</style>
{% endblock head %}

{% block header %}
    {{ header }}
{% endblock header %}

{% block content %}
        <div class="form-horizontal">
            {% for field in form %}
                <div class="control-group{% if field.errors %} error{% endif %}">
                    <label class="control-label" for="id_{{ field.html_name }}">{{ field.label }}</label>
                    <div class="controls">
                        {{ field }}
                    </div>
                </div>
            {% endfor %}
            <div class="control-group">
                <label class="control-label" for="id_rand">Play order</label>
                <div class="controls">
                    <input readonly="True" type="text" name="rand" value="{{ rand }}" id="id_rand" />
                </div>
            </div>
            <div class="form-actions form-container">
                <a class="btn" href="{% url 'display_test' test_id=test_id %}">Parent Test</a>
                {% if can_share %}
                    <a class="btn btn-primary" href="{% url 'share_test_instance' test_id=test_id test_instance_id=test_instance_id %}">Share</a>
                {% endif %}
                {% if can_export %}
                    <a class="btn btn-primary" href="{% url 'export_test_instance' test_id=test_id test_instance_id=test_instance_id %}">Export Data</a>
                {% endif %}
                {% if can_edit %}
                    <a class="btn btn-primary" href="{% url 'edit_test_instance' test_id=test_id test_instance_id=test_instance_id %}">Edit</a>
                {% endif %}
                {% if can_delete or can_unshare %}
                    <a href="#deleteModal" role="button" class="btn btn-danger" data-toggle="modal">{% if can_delete %}Delete{% else %}Stop collaborating{% endif %}</a>
                    <div id="deleteModal" class="modal hide fade" tabindex="-1" role="dialog" data-backdrop="static" keyboard="false">
                        <div class="modal-header">
                            <h3>{% if can_delete %}Delete{% else %}Stop collaborating on{% endif %} this test instance?</h3>
                        </div>
                        <div class="modal-body">
                            <p>{% if can_delete %}This cannot be undone and all related data will also be removed.{% else %}You will no longer have access to this test instance.{% endif %}</p>
                        </div>
                        <div class="modal-footer">
                            <button class="btn" data-dismiss="modal">Cancel</button>
                            <form action="{% if can_delete %}{% url 'delete_test_instance' test_id=test_id test_instance_id=test_instance_id %}{% else %}{% url 'unshare_test_instance' test_id=test_id test_instance_id=test_instance_id %}{% endif %}" method="post">
                                {% csrf_token %}
                                <input type="submit" class="btn btn-danger" value="Yes, {% if can_delete %}delete{% else %}stop collaborating{% endif %}" />
                            </form>
                        </div>
                    </div>
                {% endif %}
                {% if can_run %}
                    <a class="btn btn-success" href="{% url 'run_test_instance' test_id=test_id test_instance_id=test_instance_id %}">Start Test</a>
                {% endif %}
            </div>
        </div>
{% endblock content %}

django_source/templates/testtool/manager/log_book.html

{% extends "testtool/manager/base_log.html" %}

{% block header %}
    Log Book
{% endblock header %}

{% block table_heading %}
    All events in your recorded history
{% endblock table_heading %}

{% block no_log %}
    There is no recorded activity.
{% endblock no_log %}


django_source/templates/testtool/manager/run_test_instance.html
{% extends "testtool/manager/base_manager.html" %}

{% block header %}
    Run Test Instance
{% endblock header %}

{% block content %}
    Press 'Start Test' button at the bottom of the desktop app window.
{% endblock content %}
